import { Category } from "./types";

const mountainAnswers = [
  {
    rank: 1,
    name: "Puncak Jaya Wijaya",
    aliases: ["Puncak Jaya"],
    value: "4.884 m",
  },
  { rank: 2, name: "Kerinci", value: "3.805 m" },
  { rank: 3, name: "Rinjani", value: "3.726 m" },
  { rank: 4, name: "Semeru", value: "3.676 m" },
  { rank: 5, name: "Latimojong", value: "3.478 m" },
  { rank: 6, name: "Slamet", value: "3.432 m" },
  { rank: 7, name: "Sumbing", value: "3.371 m" },
  { rank: 8, name: "Raung", value: "3.344 m" },
  { rank: 9, name: "Arjuno", value: "3.339 m" },
  { rank: 10, name: "Lawu", value: "3.265 m" },
  { rank: 11, name: "Dempo", value: "3.173 m" },
  { rank: 12, name: "Welirang", value: "3.156 m" },
  { rank: 13, name: "Sindoro", value: "3.153 m" },
  { rank: 14, name: "Merbabu", value: "3.145 m" },
  { rank: 15, name: "Agung", value: "3.142 m" },
  { rank: 16, name: "Leuser", value: "3.119 m" },
  { rank: 17, name: "Argopuro", value: "3.088 m" },
  {
    rank: 18,
    name: "Ciremai",
    aliases: ["Cereme", "Ceremai"],
    value: "3.078 m",
  },
  { rank: 19, name: "Binaiya", value: "3.027 m" },
  { rank: 20, name: "Pangrango", value: "3.019 m" },
  { rank: 21, name: "Merapi", value: "2.968 m" },
  { rank: 22, name: "Gede", value: "2.958 m" },
  { rank: 23, name: "Talakmau", value: "2.919 m" },
  { rank: 24, name: "Puyul Sojol", value: "2.898 m" },
  { rank: 25, name: "Marapi", value: "2.891 m" },
  { rank: 26, name: "Geureudong", value: "2.885 m" },
  { rank: 27, name: "Singgalang", value: "2.877 m" },
  { rank: 28, name: "Lompobattang", value: "2.874 m" },
  { rank: 29, name: "Katopasa", value: "2.865 m" },
  { rank: 30, name: "Patah", value: "2.852 m" },
  { rank: 31, name: "Bawakaraeng", value: "2.830 m" },
  { rank: 32, name: "Cikuray", value: "2.821 m" },
  { rank: 33, name: "Peuet Sagoe", value: "2.801 m" },
  { rank: 34, name: "Ijen", value: "2.769 m" },
  { rank: 35, name: "Bulu Baria", value: "2.730 m" },
  { rank: 36, name: "Tambora", value: "2.722 m" },
  { rank: 37, name: "Papandayan", value: "2.665 m" },
  { rank: 38, name: "Kawi-Butak", value: "2.651 m" },
  { rank: 39, name: "Mekongga", value: "2.620 m" },
  { rank: 40, name: "Kendang", value: "2.608 m" },
  { rank: 41, name: "Ranti", value: "2.601 m" },
  { rank: 42, name: "Talang", value: "2.597 m" },
  { rank: 43, name: "Prau", value: "2.590 m" },
  { rank: 44, name: "Dieng", value: "2.565 m" },
  { rank: 45, name: "Wilis", value: "2.563 m" },
  { rank: 46, name: "Torenali", value: "2.526 m" },
  { rank: 47, name: "Bukit Daun", value: "2.467 m" },
  { rank: 48, name: "Bulu Torompupu", value: "2.463 m" },
  { rank: 49, name: "Sinabung", value: "2.460 m" },
  { rank: 50, name: "Sibuatan", value: "2.457 m" },
  { rank: 51, name: "Tandikat", value: "2.438 m" },
  { rank: 52, name: "Patuha", value: "2.434 m" },
  { rank: 53, name: "Tambusisi", value: "2.422 m" },
  { rank: 54, name: "Pakuwaja", value: "2.421 m" },
  { rank: 55, name: "Tangkelemboke", value: "2.421 m" },
  { rank: 56, name: "Rore Kautimbu", value: "2.400 m" },
  { rank: 57, name: "Bismo", value: "2.365 m" },
  { rank: 58, name: "Nokilalaki", value: "2.355 m" },
  { rank: 59, name: "Malabar", value: "2.343 m" },
  { rank: 60, name: "Kembang", value: "2.340 m" },
  { rank: 61, name: "Bromo", value: "2.329 m" },
  { rank: 62, name: "Bukit Raya", value: "2.278 m" },
  { rank: 63, name: "Batukaru", value: "2.276 m" },
  { rank: 64, name: "Bratan", value: "2.276 m" },
  { rank: 65, name: "Sago", value: "2.271 m" },
  { rank: 66, name: "Bulu Mopeaanooleo", value: "2.252 m" },
  { rank: 67, name: "Guntur", value: "2.249 m" },
  { rank: 68, name: "Inierie", value: "2.245 m" },
  { rank: 69, name: "Sibayak", value: "2.212 m" },
  { rank: 70, name: "Salak", value: "2.211 m" },
  { rank: 71, name: "Talagabodas", value: "2.201 m" },
  { rank: 72, name: "Rogojembangan", value: "2.177 m" },
  { rank: 73, name: "Galunggung", value: "2.168 m" },
  { rank: 74, name: "Gunung Toba", value: "2.157 m" },
  { rank: 75, name: "Abang", value: "2.151 m" },
  { rank: 76, name: "Kunyit", value: "2.151 m" },
  { rank: 77, name: "Sorikmarapi", value: "2.145 m" },
  { rank: 78, name: "Osu Porema", value: "2.140 m" },
  { rank: 79, name: "Windu", value: "2.137 m" },
  { rank: 80, name: "Sagara", value: "2.132 m" },
  { rank: 81, name: "Wayang", value: "2.132 m" },
  { rank: 82, name: "Ebulobo", value: "2.124 m" },
  { rank: 83, name: "Ranaka", value: "2.100 m" },
  { rank: 84, name: "Tanggamus", value: "2.100 m" },
  { rank: 85, name: "Catur", value: "2.096 m" },
  { rank: 86, name: "Tangkuban Perahu", value: "2.084 m" },
  { rank: 87, name: "Sanghyang", value: "2.074 m" },
  { rank: 88, name: "Pohen", value: "2.063 m" },
  { rank: 89, name: "Bukit Lumut Balai", value: "2.055 m" },
  { rank: 90, name: "Ungaran", value: "2.050 m" },
  { rank: 91, name: "Gawalise", value: "2.023 m" },
  { rank: 92, name: "Hutapanjang", value: "2.021 m" },
  { rank: 93, name: "Klabat", value: "1.995 m" },
  { rank: 94, name: "Belirang-Beriti", value: "1.958 m" },
  { rank: 95, name: "Kaba", value: "1.952 m" },
  { rank: 96, name: "Sangeang Api", value: "1.949 m" },
  { rank: 97, name: "Halimun", value: "1.929 m" },
  { rank: 98, name: "Tapak", value: "1.909 m" },
  { rank: 99, name: "Halau-Halau", value: "1.901 m" },
  { rank: 100, name: "Telomoyo", value: "1.894 m" },
];

const sourceMeta: Record<
  string,
  Pick<Category, "sourceLabel" | "sourceUrl" | "metric" | "dataAsOf">
> = {
  "film-indonesia": {
    sourceLabel: "Film Indonesia · box office snapshot",
    sourceUrl: "https://filmindonesia.or.id/",
    metric: "Penonton",
    dataAsOf: "2025",
  },
  "musisi-indonesia": {
    sourceLabel: "Soundcharts · Spotify monthly listeners",
    sourceUrl:
      "https://soundcharts.com/en/artists/spotify-monthly-listeners/country/indonesia",
    metric: "Monthly listeners",
    dataAsOf: "2026",
  },
  "youtube-indonesia": {
    sourceLabel: "Social Blade · Indonesia subscribers",
    sourceUrl: "https://socialblade.com/youtube/top/country/id/mostsubscribed",
    metric: "Subscriber",
    dataAsOf: "2026",
  },
  "kota-indonesia": {
    sourceLabel: "BPS · estimasi penduduk",
    sourceUrl: "https://www.bps.go.id/",
    metric: "Penduduk",
    dataAsOf: "2025",
  },
  "band-indonesia": {
    sourceLabel: "Soundcharts · Spotify monthly listeners",
    sourceUrl:
      "https://soundcharts.com/en/artists/spotify-monthly-listeners/country/indonesia",
    metric: "Monthly listeners",
    dataAsOf: "2026",
  },
  "makanan-indonesia": {
    sourceLabel: "Google Trends Indonesia",
    sourceUrl: "https://trends.google.com/trends/",
    metric: "Minat penelusuran",
    dataAsOf: "2025",
  },
  "mobil-indonesia": {
    sourceLabel: "GAIKINDO · retail sales by model",
    sourceUrl:
      "https://www.gaikindo.or.id/en/indonesia-automotive-retail-sales-by-model-january-december-2025/",
    metric: "Unit terjual",
    dataAsOf: "2025",
  },
  "timnas-indonesia": {
    sourceLabel: "RSSSF · Indonesia international scorers",
    sourceUrl: "https://www.rsssf.org/tablesi/ind-intres.html",
    metric: "Gol internasional",
    dataAsOf: "2026",
  },
  "wisata-indonesia": {
    sourceLabel: "BPS · statistik pariwisata",
    sourceUrl: "https://www.bps.go.id/",
    metric: "Kunjungan",
    dataAsOf: "2025",
  },
};
const supplementalAnswers: Record<string, string[]> = {
  "film-indonesia": [
    "Jumbo",
    "Pabrik Gula",
    "Komang",
    "Qodrat 2",
    "Sore: Istri dari Masa Depan",
  ],
  "musisi-indonesia": [
    "Bernadya",
    "Juicy Luicy",
    "Denny Caknan",
    "Happy Asmara",
    "Fiersa Besari",
  ],
  "youtube-indonesia": [
    "Fiki Naki",
    "Budi01 Gaming",
    "Jurnalrisa",
    "Keluarga The Onsu",
    "Raffi Ahmad",
  ],
  "kota-indonesia": [
    "Tangerang Selatan",
    "Mataram",
    "Jambi",
    "Serang",
    "Kupang",
  ],
  "band-indonesia": ["JKT48", "Tipe-X", "Armada", "Kotak", "Vierratale"],
  "makanan-indonesia": ["Siomay", "Martabak", "Nasi Uduk", "Pecel", "Tumpeng"],
  "mobil-indonesia": [
    "Toyota Calya",
    "Toyota Innova Zenix",
    "BYD Atto 1",
    "Mitsubishi Destinator",
    "Suzuki Fronx",
  ],
  "timnas-indonesia": [
    "Alberto Goncalves",
    "Ilija Spasojevic",
    "Samsul Arif",
    "Beto Goncalves",
    "Septian David Maulana",
  ],
  "wisata-indonesia": [
    "Mandalika",
    "Tanjung Puting",
    "Bintan",
    "Kepulauan Seribu",
    "Taman Nasional Baluran",
  ],
};
const entries = (names: string[]) =>
  names.map((name, index) => ({
    name,
    rank: index + 1,
    aliases:
      name === "Sheila On 7"
        ? ["SO7", "Sheila on Seven"]
        : name === "Maliq & D'Essentials"
          ? ["Maliq", "Maliq and D Essentials", "Maliq and D'essentials"]
          : undefined,
  }));
const make = (
  id: string,
  title: string,
  icon: string,
  tags: string[],
  names: string[],
  funnySubtitle: string,
  difficulty: Category["difficulty"] = "medium",
  nearMisses?: Category["nearMisses"],
): Category => ({
  id,
  slug: id,
  title,
  shortTitle: title.replace(/^100 /, ""),
  description: `Tebak ${title.toLowerCase()} yang masih masuk daftar.`,
  funnySubtitle,
  icon,
  tags,
  difficulty,
  ...sourceMeta[id],
  answers: entries([...names, ...(supplementalAnswers[id] || [])]),
  nearMisses,
});
const sourced = (
  id: string,
  title: string,
  icon: string,
  tags: string[],
  names: string[],
  funnySubtitle: string,
  sourceLabel: string,
  sourceUrl: string,
  metric: string,
  difficulty: Category["difficulty"] = "medium",
): Category => ({
  ...make(id, title, icon, tags, [], funnySubtitle, difficulty),
  metric,
  sourceLabel,
  sourceUrl,
  dataAsOf: "2026",
  answers: names.map((name, index) => ({ name, rank: index + 1 })),
});
export const categories: Category[] = [
  make(
    "film-indonesia",
    "100 Film Indonesia dengan Penonton Terbanyak",
    "🎬",
    ["Film", "Entertainment"],
    [
      "KKN di Desa Penari",
      "Agak Laen",
      "Warkop DKI Reborn: Jangkrik Boss! Part 1",
      "Dilan 1990",
      "Dilan 1991",
      "Laskar Pelangi",
      "Pengabdi Setan 2",
      "Sewu Dino",
      "Miracle in Cell No. 7",
      "Ngeri-Ngeri Sedap",
      "Habibie & Ainun",
      "Ayat-Ayat Cinta",
      "Marlina Si Pembunuh dalam Empat Babak",
      "Impetigore",
      "Yuni",
      "Nana",
      "Before, Now & Then",
      "Autobiography",
      "A Copy of My Mind",
      "Siti",
    ],
    "Penonton obscure = cuan.",
    "easy",
    [{ rank: 104, name: "Marmut Merah Jambu 2", aliases: ["MMJ 2"] }],
  ),
  make(
    "musisi-indonesia",
    "100 Artis Indonesia dengan Monthly Listeners Terbanyak",
    "🎵",
    ["Music", "Entertainment"],
    [
      "Rich Brian",
      "NIKI",
      "Pamungkas",
      "Hindia",
      "Tulus",
      "Raisa",
      "NOAH",
      "Dewa 19",
      "Sheila On 7",
      "Mahalini",
      "Tiara Andini",
      "Lyodra",
      "Feby Putri",
      "Kunto Aji",
      "Sal Priadi",
      "Maliq & D'Essentials",
      "Barasuara",
      "Danilla",
      "Lomba Sihir",
      "Mocca",
    ],
    "Galau ternyata punya leaderboard.",
    "medium",
  ),
  make(
    "youtube-indonesia",
    "100 YouTuber Indonesia dengan Subscriber Terbanyak",
    "📺",
    ["Internet", "YouTube"],
    [
      "Ricis Official",
      "Atta Halilintar",
      "Jess No Limit",
      "Frost Diamond",
      "Baim Paula",
      "Rans Entertainment",
      "MiawAug",
      "Deddy Corbuzier",
      "Nex Carlos",
      "Tanboy Kun",
      "Jerome Polin",
      "Kok Bisa?",
      "Satu Persen",
      "Kenny Austin",
      "Gita Savitri",
      "Nihongo Mantappu",
      "Tretan Universe",
      "Windah Basudara",
      "Tara Arts Game Indonesia",
      "Cameo Project",
    ],
    "Jangan lupa like, comment, subscribe.",
    "easy",
  ),
  make(
    "kota-indonesia",
    "100 Kota Indonesia dengan Penduduk Terbanyak",
    "🏙️",
    ["Geography", "Indonesia"],
    [
      "Jakarta",
      "Surabaya",
      "Bekasi",
      "Bandung",
      "Medan",
      "Tangerang",
      "Depok",
      "Semarang",
      "Makassar",
      "Palembang",
      "Bogor",
      "Batam",
      "Pekanbaru",
      "Bandar Lampung",
      "Padang",
      "Malang",
      "Samarinda",
      "Denpasar",
      "Banjarmasin",
      "Ternate",
    ],
    "Yang macet biasanya jawabannya tinggi.",
    "medium",
  ),
  {
    id: "gunung-indonesia",
    slug: "gunung-indonesia",
    title: "100 Gunung Tertinggi Indonesia",
    shortTitle: "Gunung Tertinggi Indonesia",
    description: "Tebak gunung berdasarkan urutan tinggi dari Data Gunung.",
    funnySubtitle: "Naik gunung demi trivia.",
    icon: "🏔️",
    tags: ["Geography", "Nature"],
    difficulty: "hard",
    metric: "Ketinggian",
    sourceLabel: "Data Gunung",
    sourceUrl: "https://datagunung.com/gunung",
    dataAsOf: "2026",
    answers: mountainAnswers,
  },
  make(
    "band-indonesia",
    "100 Band Indonesia Paling Populer",
    "🎸",
    ["Music", "Entertainment"],
    [
      "NOAH",
      "Dewa 19",
      "Sheila On 7",
      "Slank",
      "Ungu",
      "Padi",
      "Peterpan",
      "Kahitna",
      "Gigi",
      "Wali",
      "Nidji",
      "Radja",
      "Samsons",
      "Letto",
      "Payung Teduh",
      "Hivi!",
      "Fourtwnty",
      "Efek Rumah Kaca",
      "Sore",
      "The Adams",
    ],
    "Bukan playlist bapakmu, mungkin.",
    "medium",
  ),
  make(
    "makanan-indonesia",
    "100 Makanan Indonesia Paling Dicari",
    "🍜",
    ["Food", "Indonesia"],
    [
      "Nasi Goreng",
      "Rendang",
      "Sate",
      "Bakso",
      "Soto",
      "Mie Ayam",
      "Pempek",
      "Gudeg",
      "Rawon",
      "Gado-Gado",
      "Nasi Padang",
      "Lontong Sayur",
      "Ketoprak",
      "Tahu Tek",
      "Coto Makassar",
      "Papeda",
      "Karedok",
      "Sate Lilit",
      "Nasi Liwet",
      "Sayur Asem",
    ],
    "Lapar adalah strategi permainan.",
    "easy",
  ),
  make(
    "mobil-indonesia",
    "100 Mobil Terlaris di Indonesia",
    "🚗",
    ["Automotive", "Indonesia"],
    [
      "Toyota Avanza",
      "Honda Brio",
      "Daihatsu Sigra",
      "Toyota Innova",
      "Honda HR-V",
      "Toyota Rush",
      "Mitsubishi Xpander",
      "Suzuki Ertiga",
      "Toyota Agya",
      "Daihatsu Ayla",
      "Honda CR-V",
      "Suzuki XL7",
      "Wuling Alvez",
      "Hyundai Creta",
      "Toyota Raize",
      "Honda WR-V",
      "Mazda CX-5",
      "Nissan Livina",
      "Kia Sonet",
      "Subaru Crosstrek",
    ],
    "Cuan, cicilan, dan ranking.",
    "hard",
  ),
  make(
    "timnas-indonesia",
    "Top Skor Timnas Indonesia Sepanjang Masa",
    "⚽",
    ["Football", "Sports"],
    [
      "Bambang Pamungkas",
      "Kurniawan Dwi Yulianto",
      "Ilham Jaya Kesuma",
      "Ricky Yacobi",
      "Boaz Solossa",
      "Widodo C Putro",
      "Budi Sudarsono",
      "Rafli Mursalim",
      "Egy Maulana Vikri",
      "Irfan Bachdim",
      "Osvaldo Haay",
      "Ramadhan Sananta",
      "Witan Sulaeman",
      "Saddil Ramdani",
      "Yakob Sayuri",
      "Dendy Sulistyawan",
      "Marc Klok",
      "Ricky Kambuaya",
      "Rizky Ridho",
      "Marselino Ferdinan",
    ],
    "Garuda tahu statistik juga.",
    "hard",
  ),
  make(
    "wisata-indonesia",
    "100 Destinasi Wisata Indonesia Paling Populer",
    "🌴",
    ["Travel", "Geography"],
    [
      "Bali",
      "Raja Ampat",
      "Borobudur",
      "Labuan Bajo",
      "Bromo",
      "Lombok",
      "Yogyakarta",
      "Danau Toba",
      "Bunaken",
      "Komodo",
      "Belitung",
      "Derawan",
      "Tana Toraja",
      "Karimunjawa",
      "Wakatobi",
      "Banda Neira",
      "Kawah Ijen",
      "Pulau Weh",
      "Nusa Penida",
      "Bajo",
    ],
    "Jangan lupa oleh-oleh rank rendah.",
    "medium",
  ),
  sourced(
    "kampus-indonesia",
    "Kampus Terbaik Indonesia",
    "🎓",
    ["Education", "Indonesia"],
    [
      "Universitas Indonesia",
      "Universitas Gadjah Mada",
      "Universitas Airlangga",
      "Institut Teknologi Bandung",
      "Universitas Padjadjaran",
      "Universitas Brawijaya",
      "Universitas Diponegoro",
      "IPB University",
      "Universitas Sebelas Maret",
      "Telkom University",
      "Universitas Pendidikan Indonesia",
      "Institut Teknologi Sepuluh Nopember",
      "Universitas Hasanuddin",
      "Universitas Negeri Malang",
      "Universitas Andalas",
      "Universitas Negeri Yogyakarta",
      "Universitas Bina Nusantara",
      "Universitas Negeri Padang",
      "Universitas Syiah Kuala",
      "UIN Syarif Hidayatullah Jakarta",
      "Universitas Negeri Semarang",
      "Universitas Lampung",
      "UIN Maulana Malik Ibrahim Malang",
      "Universitas Muhammadiyah Surakarta",
      "Universitas Islam Indonesia",
    ],
    "Kampus impian, poin impian.",
    "Webometrics Indonesia",
    "https://www.webometrics.org/indonesia",
    "Peringkat kampus",
    "hard",
  ),
  sourced(
    "perusahaan-indonesia",
    "Perusahaan Terbesar Indonesia",
    "🏢",
    ["Business", "Indonesia"],
    [
      "Pertamina",
      "PLN",
      "Astra International",
      "Bank Rakyat Indonesia",
      "Bank Mandiri",
      "Telkom Indonesia",
      "MIND ID",
      "Bank Central Asia",
      "Sumber Alfaria Trijaya",
      "HM Sampoerna",
      "Indofood Sukses Makmur",
      "Gudang Garam",
      "Bank Negara Indonesia",
      "Adaro Andalan Indonesia",
      "Pupuk Indonesia",
      "Sinar Mas Agro Resources and Technology",
      "Charoen Pokphand Indonesia",
      "Erajaya Swasembada",
      "Indosat Ooredoo Hutchison",
      "Japfa Comfeed Indonesia",
      "Bayan Resources",
      "Garuda Indonesia",
      "Indah Kiat Pulp & Paper",
      "Dian Swastatika Sentosa",
      "Amman Mineral Internasional",
    ],
    "Yang besar bukan cuma papan namanya.",
    "Fortune Indonesia 100 · 2025",
    "https://ranking.fortuneidn.com/",
    "Pendapatan",
    "hard",
  ),
  sourced(
    "novel-indonesia",
    "Novel Indonesia Favorit Pembaca",
    "📚",
    ["Books", "Culture"],
    [
      "Laskar Pelangi",
      "Bumi Manusia",
      "Perahu Kertas",
      "Ayat-Ayat Cinta",
      "Negeri 5 Menara",
      "Dilan 1990",
      "Cantik Itu Luka",
      "Pulang",
      "Ronggeng Dukuh Paruk",
      "Saman",
      "Supernova: Ksatria, Puteri, dan Bintang Jatuh",
      "Aroma Karsa",
      "Filosofi Kopi",
      "Hujan",
      "Bumi",
      "Rindu",
      "Laut Bercerita",
      "Amba",
      "Orang-Orang Biasa",
      "Gadis Kretek",
      "Kubah",
      "Para Priyayi",
      "Entrok",
      "Namaku Alam",
      "Ziarah",
    ],
    "Spoiler rank-nya, bukan ceritanya.",
    "Goodreads Listopia · Novel Indonesia Terbaik",
    "https://www.goodreads.com/list/show/67567.Novel_Indonesia_Terbaik",
    "Peringkat pembaca",
    "medium",
  ),
  sourced(
    "game-populer",
    "Game PC Populer",
    "🎮",
    ["Games", "Entertainment"],
    [
      "Counter-Strike 2",
      "Dota 2",
      "PUBG: BATTLEGROUNDS",
      "Apex Legends",
      "Rust",
      "Grand Theft Auto V",
      "Stardew Valley",
      "Marvel Rivals",
      "War Thunder",
      "Baldur's Gate 3",
      "Terraria",
      "ARK: Survival Evolved",
      "Path of Exile",
      "Rainbow Six Siege",
      "Palworld",
      "The Finals",
      "Helldivers 2",
      "Monster Hunter Wilds",
      "EA Sports FC 25",
      "Football Manager 2025",
      "Cyberpunk 2077",
      "R.E.P.O.",
      "Dead by Daylight",
      "Team Fortress 2",
      "Euro Truck Simulator 2",
    ],
    "Satu lagi match, satu lagi poin.",
    "SteamDB · concurrent players snapshot",
    "https://steamdb.info/charts/",
    "Pemain bersamaan",
    "easy",
  ),
  sourced(
    "atlet-indonesia",
    "Pemain Sepak Bola Indonesia Bernilai Tinggi",
    "🥅",
    ["Football", "Sports"],
    [
      "Jay Idzes",
      "Mees Hilgers",
      "Kevin Diks",
      "Calvin Verdonk",
      "Thom Haye",
      "Maarten Paes",
      "Ragnar Oratmangoen",
      "Ole Romeny",
      "Nathan Tjoe-A-On",
      "Sandy Walsh",
      "Shayne Pattynama",
      "Eliano Reijnders",
      "Ivar Jenner",
      "Marselino Ferdinan",
      "Asnawi Mangkualam",
      "Pratama Arhan",
      "Witan Sulaeman",
      "Egy Maulana Vikri",
      "Rizky Ridho",
      "Jordi Amat",
      "Rafael Struick",
      "Ramadhan Sananta",
      "Yakob Sayuri",
      "Beckham Putra",
      "Justin Hubner",
    ],
    "Market value tidak bisa dibawa ke lapangan.",
    "Transfermarkt · market value snapshot",
    "https://www.transfermarkt.com/",
    "Nilai pasar",
    "hard",
  ),
];
export const allTags = [
  "Semua",
  ...Array.from(new Set(categories.flatMap((c) => c.tags))),
];
