import { Category } from "./types";
const entries = (names: string[]) =>
  names.map((name, index) => ({
    name,
    rank: [
      1, 4, 8, 13, 18, 24, 31, 38, 45, 52, 59, 66, 72, 78, 83, 87, 91, 94, 97,
      100,
    ][index],
    aliases:
      name === "Sheila On 7"
        ? ["SO7", "Sheila on Seven"]
        : name === "Maliq & D'Essentials"
          ? ["Maliq", "Maliq and D Essentials", "Maliq and D'essentials"]
          : undefined,
  }));
const make = (
  id: string,
  title: string,
  icon: string,
  tags: string[],
  names: string[],
  funnySubtitle: string,
  difficulty: Category["difficulty"] = "medium",
  nearMisses?: Category["nearMisses"],
): Category => ({
  id,
  slug: id,
  title,
  shortTitle: title.replace(/^100 /, ""),
  description: `Tebak ${title.toLowerCase()} yang masih masuk daftar.`,
  funnySubtitle,
  icon,
  tags,
  difficulty,
  metric: "Peringkat",
  sourceLabel: "Dataset kurasi",
  dataAsOf: "2026",
  answers: entries(names),
  nearMisses,
});
export const categories: Category[] = [
  make(
    "film-indonesia",
    "100 Film Indonesia dengan Penonton Terbanyak",
    "🎬",
    ["Film", "Entertainment"],
    [
      "KKN di Desa Penari",
      "Agak Laen",
      "Warkop DKI Reborn: Jangkrik Boss! Part 1",
      "Dilan 1990",
      "Dilan 1991",
      "Laskar Pelangi",
      "Pengabdi Setan 2",
      "Sewu Dino",
      "Miracle in Cell No. 7",
      "Ngeri-Ngeri Sedap",
      "Habibie & Ainun",
      "Ayat-Ayat Cinta",
      "Marlina Si Pembunuh dalam Empat Babak",
      "Impetigore",
      "Yuni",
      "Nana",
      "Before, Now & Then",
      "Autobiography",
      "A Copy of My Mind",
      "Siti",
    ],
    "Penonton obscure = cuan.",
    "easy",
    [{ rank: 104, name: "Marmut Merah Jambu 2", aliases: ["MMJ 2"] }],
  ),
  make(
    "musisi-indonesia",
    "100 Artis Indonesia dengan Monthly Listeners Terbanyak",
    "🎵",
    ["Music", "Entertainment"],
    [
      "Rich Brian",
      "NIKI",
      "Pamungkas",
      "Hindia",
      "Tulus",
      "Raisa",
      "NOAH",
      "Dewa 19",
      "Sheila On 7",
      "Mahalini",
      "Tiara Andini",
      "Lyodra",
      "Feby Putri",
      "Kunto Aji",
      "Sal Priadi",
      "Maliq & D'Essentials",
      "Barasuara",
      "Danilla",
      "Lomba Sihir",
      "Mocca",
    ],
    "Galau ternyata punya leaderboard.",
    "medium",
  ),
  make(
    "youtube-indonesia",
    "100 YouTuber Indonesia dengan Subscriber Terbanyak",
    "📺",
    ["Internet", "YouTube"],
    [
      "Ricis Official",
      "Atta Halilintar",
      "Jess No Limit",
      "Frost Diamond",
      "Baim Paula",
      "Rans Entertainment",
      "MiawAug",
      "Deddy Corbuzier",
      "Nex Carlos",
      "Tanboy Kun",
      "Jerome Polin",
      "Kok Bisa?",
      "Satu Persen",
      "Kenny Austin",
      "Gita Savitri",
      "Nihongo Mantappu",
      "Tretan Universe",
      "Windah Basudara",
      "Tara Arts Game Indonesia",
      "Cameo Project",
    ],
    "Jangan lupa like, comment, subscribe.",
    "easy",
  ),
  make(
    "kota-indonesia",
    "100 Kota Indonesia dengan Penduduk Terbanyak",
    "🏙️",
    ["Geography", "Indonesia"],
    [
      "Jakarta",
      "Surabaya",
      "Bekasi",
      "Bandung",
      "Medan",
      "Tangerang",
      "Depok",
      "Semarang",
      "Makassar",
      "Palembang",
      "Bogor",
      "Batam",
      "Pekanbaru",
      "Bandar Lampung",
      "Padang",
      "Malang",
      "Samarinda",
      "Denpasar",
      "Banjarmasin",
      "Ternate",
    ],
    "Yang macet biasanya jawabannya tinggi.",
    "medium",
  ),
  make(
    "gunung-indonesia",
    "100 Gunung Tertinggi Indonesia",
    "🏔️",
    ["Geography", "Nature"],
    [
      "Puncak Jaya",
      "Puncak Mandala",
      "Puncak Trikora",
      "Ngga Pilimsit",
      "Kerinci",
      "Rinjani",
      "Semeru",
      "Sanggar",
      "Latimojong",
      "Binaiya",
      "Slamet",
      "Sumbing",
      "Arjuno",
      "Raung",
      "Merbabu",
      "Lawu",
      "Ciremai",
      "Papandayan",
      "Prau",
      "Andong",
    ],
    "Naik gunung demi trivia.",
    "hard",
  ),
  make(
    "band-indonesia",
    "100 Band Indonesia Paling Populer",
    "🎸",
    ["Music", "Entertainment"],
    [
      "NOAH",
      "Dewa 19",
      "Sheila On 7",
      "Slank",
      "Ungu",
      "Padi",
      "Peterpan",
      "Kahitna",
      "Gigi",
      "Wali",
      "Nidji",
      "Radja",
      "Samsons",
      "Letto",
      "Payung Teduh",
      "Hivi!",
      "Fourtwnty",
      "Efek Rumah Kaca",
      "Sore",
      "The Adams",
    ],
    "Bukan playlist bapakmu, mungkin.",
    "medium",
  ),
  make(
    "makanan-indonesia",
    "100 Makanan Indonesia Paling Dicari",
    "🍜",
    ["Food", "Indonesia"],
    [
      "Nasi Goreng",
      "Rendang",
      "Sate",
      "Bakso",
      "Soto",
      "Mie Ayam",
      "Pempek",
      "Gudeg",
      "Rawon",
      "Gado-Gado",
      "Nasi Padang",
      "Lontong Sayur",
      "Ketoprak",
      "Tahu Tek",
      "Coto Makassar",
      "Papeda",
      "Karedok",
      "Sate Lilit",
      "Nasi Liwet",
      "Sayur Asem",
    ],
    "Lapar adalah strategi permainan.",
    "easy",
  ),
  make(
    "mobil-indonesia",
    "100 Mobil Terlaris di Indonesia",
    "🚗",
    ["Automotive", "Indonesia"],
    [
      "Toyota Avanza",
      "Honda Brio",
      "Daihatsu Sigra",
      "Toyota Innova",
      "Honda HR-V",
      "Toyota Rush",
      "Mitsubishi Xpander",
      "Suzuki Ertiga",
      "Toyota Agya",
      "Daihatsu Ayla",
      "Honda CR-V",
      "Suzuki XL7",
      "Wuling Alvez",
      "Hyundai Creta",
      "Toyota Raize",
      "Honda WR-V",
      "Mazda CX-5",
      "Nissan Livina",
      "Kia Sonet",
      "Subaru Crosstrek",
    ],
    "Cuan, cicilan, dan ranking.",
    "hard",
  ),
  make(
    "timnas-indonesia",
    "Top Skor Timnas Indonesia Sepanjang Masa",
    "⚽",
    ["Football", "Sports"],
    [
      "Bambang Pamungkas",
      "Kurniawan Dwi Yulianto",
      "Ilham Jaya Kesuma",
      "Ricky Yacobi",
      "Boaz Solossa",
      "Widodo C Putro",
      "Budi Sudarsono",
      "Rafli Mursalim",
      "Egy Maulana Vikri",
      "Irfan Bachdim",
      "Osvaldo Haay",
      "Ramadhan Sananta",
      "Witan Sulaeman",
      "Saddil Ramdani",
      "Yakob Sayuri",
      "Dendy Sulistyawan",
      "Marc Klok",
      "Ricky Kambuaya",
      "Rizky Ridho",
      "Marselino Ferdinan",
    ],
    "Garuda tahu statistik juga.",
    "hard",
  ),
  make(
    "wisata-indonesia",
    "100 Destinasi Wisata Indonesia Paling Populer",
    "🌴",
    ["Travel", "Geography"],
    [
      "Bali",
      "Raja Ampat",
      "Borobudur",
      "Labuan Bajo",
      "Bromo",
      "Lombok",
      "Yogyakarta",
      "Danau Toba",
      "Bunaken",
      "Komodo",
      "Belitung",
      "Derawan",
      "Tana Toraja",
      "Karimunjawa",
      "Wakatobi",
      "Banda Neira",
      "Kawah Ijen",
      "Pulau Weh",
      "Nusa Penida",
      "Bajo",
    ],
    "Jangan lupa oleh-oleh rank rendah.",
    "medium",
  ),
];
export const allTags = [
  "Semua",
  ...Array.from(new Set(categories.flatMap((c) => c.tags))),
];
